USE DATABASE LLM_CORTEX_DEMO_DB;
USE SCHEMA STAGE;
USE WAREHOUSE USER_STD_XSMALL_WH;

CREATE OR REPLACE TABLE LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT_CALLER (
    FILE_NAME STRING,
    CALLER_NAME STRING,
    TRANSCRIPT VARIANT
);

INSERT INTO LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT_CALLER
SELECT
    FILE_NAME,
    EXTRACT_ANSWER(
        'gpt-4',
        'What is the name of the customer speaking in this transcript? Only return the name.',
        PARSED_CONTENT:text
    ) AS CALLER_NAME,
    PARSED_CONTENT:text AS TRANSCRIPT
FROM LLM_CORTEX_DEMO_DB.STAGE.PARSED_TRANSCRIPTS;

SELECT *
FROM LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT_CALLER;