--------------------------------------------------------------------------
-- Step 1: Set Context
--------------------------------------------------------------------------
-- Sets the working environment to the correct database, schema, and warehouse.
--------------------------------------------------------------------------

USE DATABASE LLM_CORTEX_DEMO_DB;
USE SCHEMA STAGE;
USE WAREHOUSE USER_STD_XSMALL_WH;

--------------------------------------------------------------------------
-- Step 2: Create Transcript Summary Table
--------------------------------------------------------------------------
-- Creates a table named TRANSCRIPT_SUMMARY that will store:
-- - FILE_NAME: the name of the PDF file
-- - TRANSCRIPT_SUMMARY: the summary generated by Cortex
-- - TRANSCRIPT: the original transcript text
--------------------------------------------------------------------------

CREATE OR REPLACE TABLE LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT_SUMMARY 
(
    FILE_NAME VARCHAR,
    TRANSCRIPT_SUMMARY VARCHAR,
    TRANSCRIPT VARCHAR
);

--------------------------------------------------------------------------
-- Step 3: Preview Cortex Summary for a Specific File
--------------------------------------------------------------------------
-- Uses SNOWFLAKE.CORTEX.SUMMARIZE to generate a summary for a specific
-- transcript identified by FILE_NAME. This allows for initial testing and validation.
--------------------------------------------------------------------------

SELECT
    FILE_NAME,
    SNOWFLAKE.CORTEX.SUMMARIZE
    (
        TRANSCRIPT
    ) AS TRANSCRIPT_SUMMARY,
    TRANSCRIPT
FROM 
    LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT
WHERE
    FILE_NAME = 'audiofile11.pdf';

--------------------------------------------------------------------------
-- Step 4: Insert Summaries into TRANSCRIPT_SUMMARY Table
--------------------------------------------------------------------------
-- Iterates over all records in the TRANSCRIPT table and inserts the
-- generated summary along with the original transcript into the
-- TRANSCRIPT_SUMMARY table.
--------------------------------------------------------------------------

INSERT INTO LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT_SUMMARY
SELECT
    FILE_NAME,
    SNOWFLAKE.CORTEX.SUMMARIZE
    (
        TRANSCRIPT
    ) AS TRANSCRIPT_SUMMARY,
    TRANSCRIPT
FROM 
    LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT;

--------------------------------------------------------------------------
-- Step 5: Preview Transcript Summary Table
--------------------------------------------------------------------------
-- Displays all records from the TRANSCRIPT_SUMMARY table to confirm that
-- summaries were generated and stored correctly.
--------------------------------------------------------------------------

SELECT *
FROM 
    LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT_SUMMARY;

--------------------------------------------------------------------------
