USE DATABASE LLM_CORTEX_DEMO_DB;
USE SCHEMA STAGE;
USE WAREHOUSE USER_STD_XSMALL_WH;

CREATE OR REPLACE TABLE LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT_SUMMARY (
    FILE_NAME STRING,
    MAIN_COMPLAINT STRING,
    TRANSCRIPT VARIANT
);

INSERT INTO LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT_SUMMARY
SELECT
    FILE_NAME,
    SUMMARIZE(
        'gpt-4',
        'Summarize the main complaint made by the customer in this transcript.',
        PARSED_CONTENT:text
    ) AS MAIN_COMPLAINT,
    PARSED_CONTENT AS TRANSCRIPT
FROM LLM_CORTEX_DEMO_DB.STAGE.PARSED_TRANSCRIPTS;

SELECT *
FROM LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT_SUMMARY;