--------------------------------------------------------------------------
-- Step 1: Set Context
--------------------------------------------------------------------------
-- Sets the working environment to use the appropriate database, schema,
-- and compute warehouse for all subsequent operations.
--------------------------------------------------------------------------

USE DATABASE LLM_CORTEX_DEMO_DB;
USE SCHEMA STAGE;
USE WAREHOUSE USER_STD_XSMALL_WH;

--------------------------------------------------------------------------
-- Step 2: Create Transcript Sentiment Table
--------------------------------------------------------------------------
-- Creates a table named TRANSCRIPT_SENTIMENT to store:
-- - FILE_NAME: the name of the PDF file
-- - OVERALL_SENTIMENT: the sentiment score generated by Cortex
-- - TRANSCRIPT: the full text content of the transcript
--------------------------------------------------------------------------

CREATE OR REPLACE TABLE LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT_SENTIMENT 
(
    FILE_NAME VARCHAR,
    OVERALL_SENTIMENT FLOAT,
    TRANSCRIPT VARCHAR
);

--------------------------------------------------------------------------
-- Step 3: Preview Sentiment Analysis for a Specific File
--------------------------------------------------------------------------
-- Applies SNOWFLAKE.CORTEX.SENTIMENT to a single transcript for testing.
-- Returns the sentiment score and the original transcript for the specified file.
--------------------------------------------------------------------------

SELECT
    FILE_NAME,
    SNOWFLAKE.CORTEX.SENTIMENT(TRANSCRIPT) AS OVERALL_SENTIMENT,
    TRANSCRIPT
FROM 
    LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT
WHERE
    FILE_NAME = 'audiofile11.pdf';

--------------------------------------------------------------------------
-- Step 4: Insert Sentiment Analysis Results into Table
--------------------------------------------------------------------------
-- Applies sentiment analysis to all transcripts and stores the results
-- in the TRANSCRIPT_SENTIMENT table alongside the original content.
--------------------------------------------------------------------------

INSERT INTO LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT_SENTIMENT
SELECT
    FILE_NAME,
    SNOWFLAKE.CORTEX.SENTIMENT(TRANSCRIPT) AS OVERALL_SENTIMENT,
    TRANSCRIPT
FROM 
    LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT;

--------------------------------------------------------------------------
-- Step 5: Preview Transcript Sentiment Table
--------------------------------------------------------------------------
-- Displays the contents of the TRANSCRIPT_SENTIMENT table to validate
-- that sentiment scores were computed and saved successfully.
--------------------------------------------------------------------------

SELECT *
FROM LLM_CORTEX_DEMO_DB.STAGE.TRANSCRIPT_SENTIMENT;

--------------------------------------------------------------------------
