-- Extract MP3 audio files from Snowflake stage with incremental logic
INSERT INTO EXTRACT.AUDIO_FILES (
    CALL_TRANSCRIPT_ID,
    FILE_PATH,
    AUDIO_FILE,
    AUDIO_FILE_URL,
    FILE_SIZE,
    LAST_MODIFIED,
    FILE_EXTENSION
)
SELECT 
    REPLACE(UPPER(RELATIVE_PATH), '.MP3', '') AS CALL_TRANSCRIPT_ID,
    RELATIVE_PATH AS FILE_PATH,
    TO_FILE('@EXTRACT.INT_STAGE_DOC', RELATIVE_PATH) AS AUDIO_FILE,
    BUILD_STAGE_FILE_URL('@EXTRACT.INT_STAGE_DOC', RELATIVE_PATH) AS AUDIO_FILE_URL,
    SIZE AS FILE_SIZE,
    LAST_MODIFIED,
    SPLIT_PART(acRELATIVE_PATH, '.', -1) AS FILE_EXTENSION
FROM 
    DIRECTORY('@EXTRACT.INT_STAGE_DOC')
WHERE 
    UPPER(RELATIVE_PATH) LIKE '%.MP3'
    AND NOT EXISTS (
        SELECT 1 FROM EXTRACT.AUDIO_FILES t 
        WHERE t.CALL_TRANSCRIPT_ID = REPLACE(UPPER(RELATIVE_PATH), '.MP3', '')
    );